import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; // Importation globale des styles

// Importation des polices locales avec variables CSS
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Métadonnées du projet
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Courses | Education</title>
        <meta name="description" content="A comprehensive education platform" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="/assets/img/favicon.ico"
        />
        {/* Styles globaux externes */}
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/da-slider.css" />

        <link rel="stylesheet" href="/assets/css/themify-icons.css" />

        <link rel="stylesheet" href="/assets/css/gijgo.css" />
        <link rel="stylesheet" href="/assets/css/flaticon.css" />
        <link rel="stylesheet" href="/assets/css/slicknav.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* Vidéo d'arrière-plan */}
        <video autoPlay loop muted playsInline className="back">
          <source src="/video1.mp4" type="video/mp4" />
        </video>
      </body>
    </html>
  );
}
